---
topic: Welcome to saunabot

# Put your login information in here or give them to bot when it askes them.
# If you have your login information here, remember to restrict who can read this file
# login_params:
#    login: username
#    password: password
